# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from hyperplane_python_sdk.pydantic.models_tag_categorical_attribute_filter_allowed_values import ModelsTagCategoricalAttributeFilterAllowedValues
from hyperplane_python_sdk.pydantic.models_tag_categorical_attribute_filter_blocked_values import ModelsTagCategoricalAttributeFilterBlockedValues

class ModelsTagCategoricalAttributeFilter(BaseModel):
    allowed_values: ModelsTagCategoricalAttributeFilterAllowedValues = Field(alias='allowed_values')

    blocked_values: ModelsTagCategoricalAttributeFilterBlockedValues = Field(alias='blocked_values')

    # Tag name
    tag_name: str = Field(alias='tag_name')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
