# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ModelsPersonaCreateResponse(BaseModel):
    # Creation datetime of persona
    creation_datetime: str = Field(alias='creation_datetime')

    # Unique identifier for the persona
    persona_id: str = Field(alias='persona_id')

    # Name of the persona
    persona_name: str = Field(alias='persona_name')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
