# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ModelsPersonaScorePercentiles(BaseModel):
    percentile_10: typing.Optional[typing.Union[int, float]] = Field(None, alias='percentile_10')

    percentile_20: typing.Optional[typing.Union[int, float]] = Field(None, alias='percentile_20')

    percentile_30: typing.Optional[typing.Union[int, float]] = Field(None, alias='percentile_30')

    percentile_40: typing.Optional[typing.Union[int, float]] = Field(None, alias='percentile_40')

    percentile_50: typing.Optional[typing.Union[int, float]] = Field(None, alias='percentile_50')

    percentile_60: typing.Optional[typing.Union[int, float]] = Field(None, alias='percentile_60')

    percentile_70: typing.Optional[typing.Union[int, float]] = Field(None, alias='percentile_70')

    percentile_80: typing.Optional[typing.Union[int, float]] = Field(None, alias='percentile_80')

    percentile_90: typing.Optional[typing.Union[int, float]] = Field(None, alias='percentile_90')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
