# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from hyperplane_python_sdk.pydantic.models_transfer_party import ModelsTransferParty

class ModelsTransferMetadata(BaseModel):
    # Transfer payment method
    payment_method: typing.Optional[str] = Field(None, alias='payment_method')

    # Transfer inferred reason
    reason: typing.Optional[str] = Field(None, alias='reason')

    # Transfer party that receives the money
    receiver: typing.Optional[ModelsTransferParty] = Field(None, alias='receiver')

    # Transfer reference number
    reference_number: typing.Optional[str] = Field(None, alias='reference_number')

    # Transfer party that sends the money
    sender: typing.Optional[ModelsTransferParty] = Field(None, alias='sender')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
