# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from hyperplane_python_sdk.pydantic.models_tag_categorical_attribute_filter import ModelsTagCategoricalAttributeFilter
from hyperplane_python_sdk.pydantic.models_user_metadata import ModelsUserMetadata

class ModelsAutoMLRunUsersGetRequest(BaseModel):
    # List of users to return user scores for
    allow_users: typing.Optional[typing.List[ModelsUserMetadata]] = Field(None, alias='allow_users')

    # List of users to omit from returned user scores
    block_users: typing.Optional[typing.List[ModelsUserMetadata]] = Field(None, alias='block_users')

    # Categorical Filters on pf_type metadata
    tag_filters: typing.Optional[typing.List[ModelsTagCategoricalAttributeFilter]] = Field(None, alias='tag_filters')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
