# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from hyperplane_python_sdk.pydantic.models_input_label_summary import ModelsInputLabelSummary

class ModelsAutoMLLookalikeCreateResponse(BaseModel):
    # Analysis of input labels detailing amounts of labels given, amounts of labels detected, monthly breakdowns of positive rates and counts, and a breakdown of weights by label value.
    input_label_summary: ModelsInputLabelSummary = Field(alias='input_label_summary')

    # RunID is the unique identifier for the AutoML run
    run_id: str = Field(alias='run_id')

    # Description of the run
    run_description: typing.Optional[str] = Field(None, alias='run_description')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
