# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from hyperplane_python_sdk.pydantic.models_persona_create_request import ModelsPersonaCreateRequest
from hyperplane_python_sdk.pydantic.models_persona_score_statistics import ModelsPersonaScoreStatistics

class ModelsPersonaDetailsResponse(BaseModel):
    # Creation datetime of persona
    creation_datetime: str = Field(alias='creation_datetime')

    # The persona definition used to create this persona
    definition: ModelsPersonaCreateRequest = Field(alias='definition')

    # Unique identifier for the persona
    persona_id: str = Field(alias='persona_id')

    # Statistical attributes about the persona score distribution
    persona_score_statistics: ModelsPersonaScoreStatistics = Field(alias='persona_score_statistics')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
