# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from hyperplane_python_sdk.pydantic.models_pagination_metadata import ModelsPaginationMetadata
from hyperplane_python_sdk.pydantic.models_transaction_enrichment_user import ModelsTransactionEnrichmentUser

class ModelsTransactionEnrichmentUsersResponse(BaseModel):
    # Pagination metadata needed to know the next call
    pagination_metadata: ModelsPaginationMetadata = Field(alias='pagination_metadata')

    # List of users related to the transactions
    users: typing.List[ModelsTransactionEnrichmentUser] = Field(alias='users')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
