# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ModelsTransactionEnrichmentUser(BaseModel):
    # Date for first transaction registered for a given user.
    first_transaction_date: str = Field(alias='first_transaction_date')

    # Date for last transaction registered for a given user.
    last_transaction_date: str = Field(alias='last_transaction_date')

    # Unique user identifier
    user_id: str = Field(alias='user_id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
