# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from hyperplane_python_sdk.pydantic.models_user_score import ModelsUserScore

class ModelsAutoMLRunUsersGetResponse(BaseModel):
    # List of user scores
    user_scores: typing.List[ModelsUserScore] = Field(alias='user_scores')

    # Date string of last inference in `YYYY-MM-DD hh:mm:ss` format
    last_scored_date: typing.Optional[str] = Field(None, alias='last_scored_date')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
