# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from hyperplane_python_sdk.pydantic.models_top_level_category_cashflow import ModelsTopLevelCategoryCashflow

class ModelsUserCashflowPerCategoryResponse(BaseModel):
    # Inflow discriminated by category
    inflow_categories: typing.Optional[typing.List[ModelsTopLevelCategoryCashflow]] = Field(None, alias='inflow_categories')

    # Outflow discriminated by category
    outflow_categories: typing.Optional[typing.List[ModelsTopLevelCategoryCashflow]] = Field(None, alias='outflow_categories')

    # User identifier
    user_id: typing.Optional[str] = Field(None, alias='user_id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
