# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from hyperplane_python_sdk.pydantic.models_category_cashflow import ModelsCategoryCashflow

class ModelsTopLevelCategoryCashflow(BaseModel):
    # Aggregate amount for the given category
    amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='amount')

    # Detailed predicted categories under the top-level
    categories: typing.Optional[typing.List[ModelsCategoryCashflow]] = Field(None, alias='categories')

    # Human-friendly category name
    name: typing.Optional[str] = Field(None, alias='name')

    # Absolute amount flow for the category
    percentage: typing.Optional[typing.Union[int, float]] = Field(None, alias='percentage')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
