# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ModelsCashflowWindowStatistics(BaseModel):
    # Inflow amount on the given window
    inflow_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='inflow_amount')

    # Outflow amount on the given window
    outflow_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='outflow_amount')

    # End time of the given window
    window_end: typing.Optional[str] = Field(None, alias='window_end')

    # Start time of the given window
    window_start: typing.Optional[str] = Field(None, alias='window_start')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
