# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from hyperplane_python_sdk.pydantic.models_user_persona_score import ModelsUserPersonaScore

class ModelsUserPersonasResponse(BaseModel):
    # Ranked list of personas for this user
    persona_scores: typing.List[ModelsUserPersonaScore] = Field(alias='persona_scores')

    # Unique identifier for the user
    user_id: str = Field(alias='user_id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
