# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ModelsTransferParty(BaseModel):
    # Party account number
    account_number: typing.Optional[str] = Field(None, alias='account_number')

    # Party branch number
    branch_number: typing.Optional[str] = Field(None, alias='branch_number')

    # Party document name
    document_name: typing.Optional[str] = Field(None, alias='document_name')

    # Party document number
    document_number: typing.Optional[str] = Field(None, alias='document_number')

    # Party name
    name: typing.Optional[str] = Field(None, alias='name')

    # Party routing number
    routing_number: typing.Optional[str] = Field(None, alias='routing_number')

    # Party ISPB routing number
    routing_number__i_s_p_b: typing.Optional[str] = Field(None, alias='routing_number_ISPB')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
