# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from hyperplane_python_sdk.pydantic.models_pagination_metadata import ModelsPaginationMetadata
from hyperplane_python_sdk.pydantic.models_transaction_enrichment_response import ModelsTransactionEnrichmentResponse

class ModelsUserTransactionsResponse(BaseModel):
    # List of enriched transactions
    enriched_transactions: typing.List[ModelsTransactionEnrichmentResponse] = Field(alias='enriched_transactions')

    # Pagination metadata needed to know the next call
    pagination_metadata: ModelsPaginationMetadata = Field(alias='pagination_metadata')

    # User identifier
    user_id: str = Field(alias='user_id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
