# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import hyperplane_python_sdk
from hyperplane_python_sdk.model.api_err_response import ApiErrResponse
from hyperplane_python_sdk import configuration


class TestApiErrResponse(unittest.TestCase):
    """ApiErrResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
