# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import hyperplane_python_sdk
from hyperplane_python_sdk.model.auto_ml_service_get_run_status_batch_scores_response import AutoMlServiceGetRunStatusBatchScoresResponse
from hyperplane_python_sdk import configuration


class TestAutoMlServiceGetRunStatusBatchScoresResponse(unittest.TestCase):
    """AutoMlServiceGetRunStatusBatchScoresResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
