# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import hyperplane_python_sdk
from hyperplane_python_sdk.model.models_auto_ml_run_metrics_cumulative_positive_rate import ModelsAutoMLRunMetricsCumulativePositiveRate
from hyperplane_python_sdk import configuration


class TestModelsAutoMLRunMetricsCumulativePositiveRate(unittest.TestCase):
    """ModelsAutoMLRunMetricsCumulativePositiveRate unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
