# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import hyperplane_python_sdk
from hyperplane_python_sdk.model.models_tag_categorical_attribute_filter_allowed_values import ModelsTagCategoricalAttributeFilterAllowedValues
from hyperplane_python_sdk import configuration


class TestModelsTagCategoricalAttributeFilterAllowedValues(unittest.TestCase):
    """ModelsTagCategoricalAttributeFilterAllowedValues unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
