# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from hyperplane_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from hyperplane_python_sdk.api_response import AsyncGeneratorResponse
from hyperplane_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hyperplane_python_sdk import schemas  # noqa: F401

from hyperplane_python_sdk.model.models_persona_create_response import ModelsPersonaCreateResponse as ModelsPersonaCreateResponseSchema
from hyperplane_python_sdk.model.models_persona_create_request import ModelsPersonaCreateRequest as ModelsPersonaCreateRequestSchema
from hyperplane_python_sdk.model.api_err_response import ApiErrResponse as ApiErrResponseSchema
from hyperplane_python_sdk.model.models_persona_create_request_locations import ModelsPersonaCreateRequestLocations as ModelsPersonaCreateRequestLocationsSchema
from hyperplane_python_sdk.model.models_facet_weight_object import ModelsFacetWeightObject as ModelsFacetWeightObjectSchema

from hyperplane_python_sdk.type.models_persona_create_request import ModelsPersonaCreateRequest
from hyperplane_python_sdk.type.api_err_response import ApiErrResponse
from hyperplane_python_sdk.type.models_persona_create_response import ModelsPersonaCreateResponse
from hyperplane_python_sdk.type.models_facet_weight_object import ModelsFacetWeightObject
from hyperplane_python_sdk.type.models_persona_create_request_locations import ModelsPersonaCreateRequestLocations

from ...api_client import Dictionary
from hyperplane_python_sdk.pydantic.models_persona_create_request import ModelsPersonaCreateRequest as ModelsPersonaCreateRequestPydantic
from hyperplane_python_sdk.pydantic.models_persona_create_request_locations import ModelsPersonaCreateRequestLocations as ModelsPersonaCreateRequestLocationsPydantic
from hyperplane_python_sdk.pydantic.models_facet_weight_object import ModelsFacetWeightObject as ModelsFacetWeightObjectPydantic
from hyperplane_python_sdk.pydantic.models_persona_create_response import ModelsPersonaCreateResponse as ModelsPersonaCreateResponsePydantic
from hyperplane_python_sdk.pydantic.api_err_response import ApiErrResponse as ApiErrResponsePydantic

from . import path

# Query params
ModelVersionSchema = schemas.StrSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'model_version': typing.Union[ModelVersionSchema, str, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_model_version = api_client.QueryParameter(
    name="model_version",
    style=api_client.ParameterStyle.FORM,
    schema=ModelVersionSchema,
    explode=True,
)
# body param
SchemaForRequestBodyApplicationJson = ModelsPersonaCreateRequestSchema


request_body_models_persona_create_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
_auth = [
    'PASETO',
]
SchemaFor200ResponseBodyApplicationJson = ModelsPersonaCreateResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: ModelsPersonaCreateResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: ModelsPersonaCreateResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor400ResponseBodyApplicationJson = ApiErrResponseSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: ApiErrResponse


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: ApiErrResponse


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
SchemaFor409ResponseBodyApplicationJson = ApiErrResponseSchema


@dataclass
class ApiResponseFor409(api_client.ApiResponse):
    body: ApiErrResponse


@dataclass
class ApiResponseFor409Async(api_client.AsyncApiResponse):
    body: ApiErrResponse


_response_for_409 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor409,
    response_cls_async=ApiResponseFor409Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor409ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '400': _response_for_400,
    '409': _response_for_409,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _create_definition_mapped_args(
        self,
        persona_name: str,
        company_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        demographic_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        interest_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        locations: typing.Optional[ModelsPersonaCreateRequestLocations] = None,
        pre_defined_personas: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        model_version: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _body = {}
        if company_facets is not None:
            _body["company_facets"] = company_facets
        if demographic_facets is not None:
            _body["demographic_facets"] = demographic_facets
        if interest_facets is not None:
            _body["interest_facets"] = interest_facets
        if locations is not None:
            _body["locations"] = locations
        if persona_name is not None:
            _body["persona_name"] = persona_name
        if pre_defined_personas is not None:
            _body["pre_defined_personas"] = pre_defined_personas
        args.body = _body
        if model_version is not None:
            _query_params["model_version"] = model_version
        args.query = _query_params
        return args

    async def _acreate_definition_oapg(
        self,
        body: typing.Any = None,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Create a persona definition.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_model_version,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/persona',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_models_persona_create_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _create_definition_oapg(
        self,
        body: typing.Any = None,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Create a persona definition.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_model_version,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/persona',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_models_persona_create_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class CreateDefinitionRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def acreate_definition(
        self,
        persona_name: str,
        company_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        demographic_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        interest_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        locations: typing.Optional[ModelsPersonaCreateRequestLocations] = None,
        pre_defined_personas: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        model_version: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_definition_mapped_args(
            persona_name=persona_name,
            company_facets=company_facets,
            demographic_facets=demographic_facets,
            interest_facets=interest_facets,
            locations=locations,
            pre_defined_personas=pre_defined_personas,
            model_version=model_version,
        )
        return await self._acreate_definition_oapg(
            body=args.body,
            query_params=args.query,
            **kwargs,
        )
    
    def create_definition(
        self,
        persona_name: str,
        company_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        demographic_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        interest_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        locations: typing.Optional[ModelsPersonaCreateRequestLocations] = None,
        pre_defined_personas: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        model_version: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_definition_mapped_args(
            persona_name=persona_name,
            company_facets=company_facets,
            demographic_facets=demographic_facets,
            interest_facets=interest_facets,
            locations=locations,
            pre_defined_personas=pre_defined_personas,
            model_version=model_version,
        )
        return self._create_definition_oapg(
            body=args.body,
            query_params=args.query,
        )

class CreateDefinition(BaseApi):

    async def acreate_definition(
        self,
        persona_name: str,
        company_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        demographic_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        interest_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        locations: typing.Optional[ModelsPersonaCreateRequestLocations] = None,
        pre_defined_personas: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        model_version: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> ModelsPersonaCreateResponsePydantic:
        raw_response = await self.raw.acreate_definition(
            persona_name=persona_name,
            company_facets=company_facets,
            demographic_facets=demographic_facets,
            interest_facets=interest_facets,
            locations=locations,
            pre_defined_personas=pre_defined_personas,
            model_version=model_version,
            **kwargs,
        )
        if validate:
            return ModelsPersonaCreateResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(ModelsPersonaCreateResponsePydantic, raw_response.body)
    
    
    def create_definition(
        self,
        persona_name: str,
        company_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        demographic_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        interest_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        locations: typing.Optional[ModelsPersonaCreateRequestLocations] = None,
        pre_defined_personas: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        model_version: typing.Optional[str] = None,
        validate: bool = False,
    ) -> ModelsPersonaCreateResponsePydantic:
        raw_response = self.raw.create_definition(
            persona_name=persona_name,
            company_facets=company_facets,
            demographic_facets=demographic_facets,
            interest_facets=interest_facets,
            locations=locations,
            pre_defined_personas=pre_defined_personas,
            model_version=model_version,
        )
        if validate:
            return ModelsPersonaCreateResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(ModelsPersonaCreateResponsePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        persona_name: str,
        company_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        demographic_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        interest_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        locations: typing.Optional[ModelsPersonaCreateRequestLocations] = None,
        pre_defined_personas: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        model_version: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_definition_mapped_args(
            persona_name=persona_name,
            company_facets=company_facets,
            demographic_facets=demographic_facets,
            interest_facets=interest_facets,
            locations=locations,
            pre_defined_personas=pre_defined_personas,
            model_version=model_version,
        )
        return await self._acreate_definition_oapg(
            body=args.body,
            query_params=args.query,
            **kwargs,
        )
    
    def post(
        self,
        persona_name: str,
        company_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        demographic_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        interest_facets: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        locations: typing.Optional[ModelsPersonaCreateRequestLocations] = None,
        pre_defined_personas: typing.Optional[typing.List[ModelsFacetWeightObject]] = None,
        model_version: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_definition_mapped_args(
            persona_name=persona_name,
            company_facets=company_facets,
            demographic_facets=demographic_facets,
            interest_facets=interest_facets,
            locations=locations,
            pre_defined_personas=pre_defined_personas,
            model_version=model_version,
        )
        return self._create_definition_oapg(
            body=args.body,
            query_params=args.query,
        )

