# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredModelsLocation(TypedDict):
    pass

class OptionalModelsLocation(TypedDict, total=False):
    # City name
    city: str

    # IBGE city code
    city_code: str

    # Country name
    country: str

    # Full address (e.g., Av. Lúcio Costa 1234, Copacabana, Rio de Janeiro, Brasil)
    full_address: str

    # Location latitude
    latitude: typing.Union[int, float]

    # Location longitude
    longitude: typing.Union[int, float]

    # Postal code (i.e., CEP, e.g., '22620-171')
    postal_code: str

    # Primary address (e.g., Av. Lúcio Costa, 1234)
    primary_address: str

    # State name
    state: str

    # Type of location (e.g., personal, home, business, ...)
    type: str

class ModelsLocation(RequiredModelsLocation, OptionalModelsLocation):
    pass
