# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredModelsNumericalAttributeFilter(TypedDict):
    # Max attribute value
    max_value: typing.Union[int, float]

    # Min attribute value
    min_value: typing.Union[int, float]

class OptionalModelsNumericalAttributeFilter(TypedDict, total=False):
    pass

class ModelsNumericalAttributeFilter(RequiredModelsNumericalAttributeFilter, OptionalModelsNumericalAttributeFilter):
    pass
