# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hyperplane_python_sdk.type.models_pagination_metadata import ModelsPaginationMetadata
from hyperplane_python_sdk.type.models_transaction_enrichment_user import ModelsTransactionEnrichmentUser

class RequiredModelsTransactionEnrichmentUsersResponse(TypedDict):
    # Pagination metadata needed to know the next call
    pagination_metadata: ModelsPaginationMetadata

    # List of users related to the transactions
    users: typing.List[ModelsTransactionEnrichmentUser]

class OptionalModelsTransactionEnrichmentUsersResponse(TypedDict, total=False):
    pass

class ModelsTransactionEnrichmentUsersResponse(RequiredModelsTransactionEnrichmentUsersResponse, OptionalModelsTransactionEnrichmentUsersResponse):
    pass
