# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hyperplane_python_sdk.type.models_auto_ml_run_summary import ModelsAutoMLRunSummary

class RequiredModelsAutoMLRunsGetResponse(TypedDict):
    # List of AutoML run summaries
    runs: typing.List[ModelsAutoMLRunSummary]

class OptionalModelsAutoMLRunsGetResponse(TypedDict, total=False):
    pass

class ModelsAutoMLRunsGetResponse(RequiredModelsAutoMLRunsGetResponse, OptionalModelsAutoMLRunsGetResponse):
    pass
