# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredModelsPersonaCreateResponse(TypedDict):
    # Creation datetime of persona
    creation_datetime: str

    # Unique identifier for the persona
    persona_id: str

    # Name of the persona
    persona_name: str

class OptionalModelsPersonaCreateResponse(TypedDict, total=False):
    pass

class ModelsPersonaCreateResponse(RequiredModelsPersonaCreateResponse, OptionalModelsPersonaCreateResponse):
    pass
