# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hyperplane_python_sdk.type.models_input_label_summary import ModelsInputLabelSummary

class RequiredModelsAutoMLLookalikeCreateResponse(TypedDict):
    # Analysis of input labels detailing amounts of labels given, amounts of labels detected, monthly breakdowns of positive rates and counts, and a breakdown of weights by label value.
    input_label_summary: ModelsInputLabelSummary

    # RunID is the unique identifier for the AutoML run
    run_id: str

class OptionalModelsAutoMLLookalikeCreateResponse(TypedDict, total=False):
    # Description of the run
    run_description: str

class ModelsAutoMLLookalikeCreateResponse(RequiredModelsAutoMLLookalikeCreateResponse, OptionalModelsAutoMLLookalikeCreateResponse):
    pass
