# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredModelsUserPersonaScore(TypedDict):
    # Unique identifier for the persona
    persona_id: str

    # Name of the persona
    persona_name: str

class OptionalModelsUserPersonaScore(TypedDict, total=False):
    # Relevance score of user in this persona. In range `[0,1]`
    persona_score: typing.Union[int, float]

class ModelsUserPersonaScore(RequiredModelsUserPersonaScore, OptionalModelsUserPersonaScore):
    pass
