# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hyperplane_python_sdk.type.models_auto_ml_run_metrics_cumulative_positive_rate import ModelsAutoMLRunMetricsCumulativePositiveRate
from hyperplane_python_sdk.type.models_auto_ml_run_metrics_positive_rate_by_decile import ModelsAutoMLRunMetricsPositiveRateByDecile

class RequiredModelsAutoMLRunMetrics(TypedDict):
    pass

class OptionalModelsAutoMLRunMetrics(TypedDict, total=False):
    cumulative_positive_rate: ModelsAutoMLRunMetricsCumulativePositiveRate

    # The percentage of users with positive label in the test set.
    label_positive_rate: typing.Union[int, float]

    positive_rate_by_decile: ModelsAutoMLRunMetricsPositiveRateByDecile

    # AUC of the test set
    test_auc: typing.Union[int, float]

    # KS of the test set
    test_ks: typing.Union[int, float]

    # AUC of the training set
    train_auc: typing.Union[int, float]

    # KS of the training set
    train_ks: typing.Union[int, float]

class ModelsAutoMLRunMetrics(RequiredModelsAutoMLRunMetrics, OptionalModelsAutoMLRunMetrics):
    pass
