# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hyperplane_python_sdk.type.models_category_cashflow import ModelsCategoryCashflow

class RequiredModelsTopLevelCategoryCashflow(TypedDict):
    pass

class OptionalModelsTopLevelCategoryCashflow(TypedDict, total=False):
    # Aggregate amount for the given category
    amount: typing.Union[int, float]

    # Detailed predicted categories under the top-level
    categories: typing.List[ModelsCategoryCashflow]

    # Human-friendly category name
    name: str

    # Absolute amount flow for the category
    percentage: typing.Union[int, float]

class ModelsTopLevelCategoryCashflow(RequiredModelsTopLevelCategoryCashflow, OptionalModelsTopLevelCategoryCashflow):
    pass
