# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hyperplane_python_sdk.type.models_tag_categorical_attribute_filter import ModelsTagCategoricalAttributeFilter
from hyperplane_python_sdk.type.models_user_metadata import ModelsUserMetadata

class RequiredModelsAutoMLRunUsersGetRequest(TypedDict):
    pass

class OptionalModelsAutoMLRunUsersGetRequest(TypedDict, total=False):
    # List of users to return user scores for
    allow_users: typing.List[ModelsUserMetadata]

    # List of users to omit from returned user scores
    block_users: typing.List[ModelsUserMetadata]

    # Categorical Filters on pf_type metadata
    tag_filters: typing.List[ModelsTagCategoricalAttributeFilter]

class ModelsAutoMLRunUsersGetRequest(RequiredModelsAutoMLRunUsersGetRequest, OptionalModelsAutoMLRunUsersGetRequest):
    pass
