# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hyperplane_python_sdk.type.models_tag_categorical_attribute_filter_allowed_values import ModelsTagCategoricalAttributeFilterAllowedValues
from hyperplane_python_sdk.type.models_tag_categorical_attribute_filter_blocked_values import ModelsTagCategoricalAttributeFilterBlockedValues

class RequiredModelsTagCategoricalAttributeFilter(TypedDict):
    allowed_values: ModelsTagCategoricalAttributeFilterAllowedValues

    blocked_values: ModelsTagCategoricalAttributeFilterBlockedValues

    # Tag name
    tag_name: str

class OptionalModelsTagCategoricalAttributeFilter(TypedDict, total=False):
    pass

class ModelsTagCategoricalAttributeFilter(RequiredModelsTagCategoricalAttributeFilter, OptionalModelsTagCategoricalAttributeFilter):
    pass
