# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredModelsUserMetadata(TypedDict):
    # UserID is the unique identifier for the user
    user_id: str

class OptionalModelsUserMetadata(TypedDict, total=False):
    pass

class ModelsUserMetadata(RequiredModelsUserMetadata, OptionalModelsUserMetadata):
    pass
