# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hyperplane_python_sdk.type.models_pagination_metadata import ModelsPaginationMetadata
from hyperplane_python_sdk.type.models_transaction_enrichment_response import ModelsTransactionEnrichmentResponse

class RequiredModelsUserTransactionsResponse(TypedDict):
    # List of enriched transactions
    enriched_transactions: typing.List[ModelsTransactionEnrichmentResponse]

    # Pagination metadata needed to know the next call
    pagination_metadata: ModelsPaginationMetadata

    # User identifier
    user_id: str

class OptionalModelsUserTransactionsResponse(TypedDict, total=False):
    pass

class ModelsUserTransactionsResponse(RequiredModelsUserTransactionsResponse, OptionalModelsUserTransactionsResponse):
    pass
