# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hyperplane_python_sdk.type.models_auto_ml_run_metrics import ModelsAutoMLRunMetrics
from hyperplane_python_sdk.type.models_input_label_summary import ModelsInputLabelSummary

class RequiredModelsAutoMLRunSummary(TypedDict):
    # RunDescription is the description of the AutoML training run
    run_description: str

    # RunID is the unique identifier for the AutoML run
    run_id: str

    # RunStatus is the status of the AutoML training run
    status: str

    # Timestamp is the time when the training run began
    timestamp: str

class OptionalModelsAutoMLRunSummary(TypedDict, total=False):
    # Engagement type of this product run
    engagement_type: str

    # Analysis of input labels detailing amounts of labels given, amounts of labels detected, monthly breakdowns of positive rates and counts, and a breakdown of weights by label value.
    input_label_summary: ModelsInputLabelSummary

    # NumberOfInferenceUsers is the number of users in model inference
    number_of_inference_users: int

    # NumberOfTrainUsers is the number of users in model training
    number_of_train_users: int

    # RunMetrics is the metrics of the AutoML training run
    run_metrics: ModelsAutoMLRunMetrics

class ModelsAutoMLRunSummary(RequiredModelsAutoMLRunSummary, OptionalModelsAutoMLRunSummary):
    pass
