# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredModelsPercentileScore(TypedDict):
    pass

class OptionalModelsPercentileScore(TypedDict, total=False):
    # Percentile for which the score is being fetched
    percentile: typing.Union[int, float]

    # Score calculated for the given percentile
    score: typing.Union[int, float]

class ModelsPercentileScore(RequiredModelsPercentileScore, OptionalModelsPercentileScore):
    pass
