# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredModelsTransactionEnrichmentStatisticsResponse(TypedDict):
    # Number of transactions in the module
    transaction_count: int

    # Number of distinct users in the module
    user_reach: int

class OptionalModelsTransactionEnrichmentStatisticsResponse(TypedDict, total=False):
    pass

class ModelsTransactionEnrichmentStatisticsResponse(RequiredModelsTransactionEnrichmentStatisticsResponse, OptionalModelsTransactionEnrichmentStatisticsResponse):
    pass
