# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hyperplane_python_sdk.type.models_persona_create_request import ModelsPersonaCreateRequest
from hyperplane_python_sdk.type.models_persona_score_statistics import ModelsPersonaScoreStatistics

class RequiredModelsPersonaDetailsResponse(TypedDict):
    # Creation datetime of persona
    creation_datetime: str

    # The persona definition used to create this persona
    definition: ModelsPersonaCreateRequest

    # Unique identifier for the persona
    persona_id: str

    # Statistical attributes about the persona score distribution
    persona_score_statistics: ModelsPersonaScoreStatistics

class OptionalModelsPersonaDetailsResponse(TypedDict, total=False):
    pass

class ModelsPersonaDetailsResponse(RequiredModelsPersonaDetailsResponse, OptionalModelsPersonaDetailsResponse):
    pass
