# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hyperplane_python_sdk.type.models_user_metadata import ModelsUserMetadata

class RequiredModelsAutoMLUsersGetResponse(TypedDict):
    # List of users' metadata
    user_list: typing.List[ModelsUserMetadata]

class OptionalModelsAutoMLUsersGetResponse(TypedDict, total=False):
    pass

class ModelsAutoMLUsersGetResponse(RequiredModelsAutoMLUsersGetResponse, OptionalModelsAutoMLUsersGetResponse):
    pass
