# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hyperplane_python_sdk.type.models_location import ModelsLocation
from hyperplane_python_sdk.type.models_merchant_info import ModelsMerchantInfo
from hyperplane_python_sdk.type.models_transfer_metadata import ModelsTransferMetadata

class RequiredModelsTransactionEnrichmentResponse(TypedDict):
    pass

class OptionalModelsTransactionEnrichmentResponse(TypedDict, total=False):
    # Transaction description
    description: str

    # Amount of transaction
    amount: typing.Union[int, float]

    # Category enum of transaction
    category: str

    # Category human-readable name of transaction
    category_name: str

    # Transaction currency
    currency: str

    # Current installment. If 0, it is not an installment
    current_installment: int

    # Date of transaction
    date: str

    # First installment date, that is, the purchase date
    installment_start_date: str

    # Contains metadata about the merchant, if available.
    merchant_info: ModelsMerchantInfo

    # Number of installments
    number_of_installments: int

    # Sum of amounts for all installments
    total_installed_amount: typing.Union[int, float]

    # Unique transaction id
    transaction_id: str

    # Location where the transaction happened
    transaction_location: ModelsLocation

    # Transaction status
    transaction_status: str

    # Contains metadata about the payment method, the sender, and the receiver.
    transfer_metadata: ModelsTransferMetadata

class ModelsTransactionEnrichmentResponse(RequiredModelsTransactionEnrichmentResponse, OptionalModelsTransactionEnrichmentResponse):
    pass
