# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hyperplane_python_sdk.type.models_categorical_attribute_filter_allowed_values import ModelsCategoricalAttributeFilterAllowedValues
from hyperplane_python_sdk.type.models_categorical_attribute_filter_blocked_values import ModelsCategoricalAttributeFilterBlockedValues

class RequiredModelsCategoricalAttributeFilter(TypedDict):
    allowed_values: ModelsCategoricalAttributeFilterAllowedValues

    blocked_values: ModelsCategoricalAttributeFilterBlockedValues

class OptionalModelsCategoricalAttributeFilter(TypedDict, total=False):
    pass

class ModelsCategoricalAttributeFilter(RequiredModelsCategoricalAttributeFilter, OptionalModelsCategoricalAttributeFilter):
    pass
