# coding: utf-8
"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from hyperplane_python_sdk.client_custom import ClientCustom
from hyperplane_python_sdk.configuration import Configuration
from hyperplane_python_sdk.api_client import ApiClient
from hyperplane_python_sdk.type_util import copy_signature
from hyperplane_python_sdk.apis.tags.auth_api import AuthApi
from hyperplane_python_sdk.apis.tags.auto_ml_service_api import AutoMLServiceApi
from hyperplane_python_sdk.apis.tags.client_api import ClientApi
from hyperplane_python_sdk.apis.tags.enriched_transactions_api import EnrichedTransactionsApi
from hyperplane_python_sdk.apis.tags.health_api import HealthApi
from hyperplane_python_sdk.apis.tags.personas_api import PersonasApi
from hyperplane_python_sdk.apis.tags.statistics_api import StatisticsApi
from hyperplane_python_sdk.apis.tags.users_api import UsersApi



class Hyperplane(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.auth: AuthApi = AuthApi(api_client)
        self.auto_ml_service: AutoMLServiceApi = AutoMLServiceApi(api_client)
        self.client: ClientApi = ClientApi(api_client)
        self.enriched_transactions: EnrichedTransactionsApi = EnrichedTransactionsApi(api_client)
        self.health: HealthApi = HealthApi(api_client)
        self.personas: PersonasApi = PersonasApi(api_client)
        self.statistics: StatisticsApi = StatisticsApi(api_client)
        self.users: UsersApi = UsersApi(api_client)
