# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hyperplane_python_sdk import schemas  # noqa: F401


class ModelsAutoMLLookalikeCreateRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "engagement_type",
            "positive_label_users",
        }
        
        class properties:
            engagement_type = schemas.StrSchema
            
            
            class positive_label_users(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ModelsLookalikeLabel']:
                        return ModelsLookalikeLabel
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ModelsLookalikeLabel'], typing.List['ModelsLookalikeLabel']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'positive_label_users':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ModelsLookalikeLabel':
                    return super().__getitem__(i)
            
            
            class negative_label_users(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ModelsLookalikeLabel']:
                        return ModelsLookalikeLabel
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ModelsLookalikeLabel'], typing.List['ModelsLookalikeLabel']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'negative_label_users':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ModelsLookalikeLabel':
                    return super().__getitem__(i)
            run_description = schemas.StrSchema
            __annotations__ = {
                "engagement_type": engagement_type,
                "positive_label_users": positive_label_users,
                "negative_label_users": negative_label_users,
                "run_description": run_description,
            }
    
    engagement_type: MetaOapg.properties.engagement_type
    positive_label_users: MetaOapg.properties.positive_label_users
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["engagement_type"]) -> MetaOapg.properties.engagement_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["positive_label_users"]) -> MetaOapg.properties.positive_label_users: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["negative_label_users"]) -> MetaOapg.properties.negative_label_users: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["run_description"]) -> MetaOapg.properties.run_description: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["engagement_type", "positive_label_users", "negative_label_users", "run_description", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["engagement_type"]) -> MetaOapg.properties.engagement_type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["positive_label_users"]) -> MetaOapg.properties.positive_label_users: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["negative_label_users"]) -> typing.Union[MetaOapg.properties.negative_label_users, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["run_description"]) -> typing.Union[MetaOapg.properties.run_description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["engagement_type", "positive_label_users", "negative_label_users", "run_description", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        engagement_type: typing.Union[MetaOapg.properties.engagement_type, str, ],
        positive_label_users: typing.Union[MetaOapg.properties.positive_label_users, list, tuple, ],
        negative_label_users: typing.Union[MetaOapg.properties.negative_label_users, list, tuple, schemas.Unset] = schemas.unset,
        run_description: typing.Union[MetaOapg.properties.run_description, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelsAutoMLLookalikeCreateRequest':
        return super().__new__(
            cls,
            *args,
            engagement_type=engagement_type,
            positive_label_users=positive_label_users,
            negative_label_users=negative_label_users,
            run_description=run_description,
            _configuration=_configuration,
            **kwargs,
        )

from hyperplane_python_sdk.model.models_lookalike_label import ModelsLookalikeLabel
