# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hyperplane_python_sdk import schemas  # noqa: F401


class ModelsBatchUserPersonasRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "user_ids",
        }
        
        class properties:
        
            @staticmethod
            def user_ids() -> typing.Type['ModelsBatchUserPersonasRequestUserIds']:
                return ModelsBatchUserPersonasRequestUserIds
            __annotations__ = {
                "user_ids": user_ids,
            }
    
    user_ids: 'ModelsBatchUserPersonasRequestUserIds'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["user_ids"]) -> 'ModelsBatchUserPersonasRequestUserIds': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["user_ids", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["user_ids"]) -> 'ModelsBatchUserPersonasRequestUserIds': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["user_ids", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        user_ids: 'ModelsBatchUserPersonasRequestUserIds',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelsBatchUserPersonasRequest':
        return super().__new__(
            cls,
            *args,
            user_ids=user_ids,
            _configuration=_configuration,
            **kwargs,
        )

from hyperplane_python_sdk.model.models_batch_user_personas_request_user_ids import ModelsBatchUserPersonasRequestUserIds
