# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hyperplane_python_sdk import schemas  # noqa: F401


class ModelsUserPersonasResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Response of personas linked to a given user
    """


    class MetaOapg:
        required = {
            "user_id",
            "persona_scores",
        }
        
        class properties:
            
            
            class persona_scores(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ModelsUserPersonaScore']:
                        return ModelsUserPersonaScore
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ModelsUserPersonaScore'], typing.List['ModelsUserPersonaScore']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'persona_scores':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ModelsUserPersonaScore':
                    return super().__getitem__(i)
            user_id = schemas.StrSchema
            __annotations__ = {
                "persona_scores": persona_scores,
                "user_id": user_id,
            }
    
    user_id: MetaOapg.properties.user_id
    persona_scores: MetaOapg.properties.persona_scores
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["persona_scores"]) -> MetaOapg.properties.persona_scores: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["user_id"]) -> MetaOapg.properties.user_id: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["persona_scores", "user_id", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["persona_scores"]) -> MetaOapg.properties.persona_scores: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["user_id"]) -> MetaOapg.properties.user_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["persona_scores", "user_id", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        user_id: typing.Union[MetaOapg.properties.user_id, str, ],
        persona_scores: typing.Union[MetaOapg.properties.persona_scores, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelsUserPersonasResponse':
        return super().__new__(
            cls,
            *args,
            user_id=user_id,
            persona_scores=persona_scores,
            _configuration=_configuration,
            **kwargs,
        )

from hyperplane_python_sdk.model.models_user_persona_score import ModelsUserPersonaScore
