# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hyperplane_python_sdk import schemas  # noqa: F401


class ModelsUserTransactionsStatisticsResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Transaction statistics for a given user
    """


    class MetaOapg:
        required = {
            "transaction_count",
        }
        
        class properties:
            transaction_count = schemas.IntSchema
            average_transaction_value = schemas.NumberSchema
            median_transaction_value = schemas.NumberSchema
            __annotations__ = {
                "transaction_count": transaction_count,
                "average_transaction_value": average_transaction_value,
                "median_transaction_value": median_transaction_value,
            }
    
    transaction_count: MetaOapg.properties.transaction_count
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transaction_count"]) -> MetaOapg.properties.transaction_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["average_transaction_value"]) -> MetaOapg.properties.average_transaction_value: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["median_transaction_value"]) -> MetaOapg.properties.median_transaction_value: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["transaction_count", "average_transaction_value", "median_transaction_value", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transaction_count"]) -> MetaOapg.properties.transaction_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["average_transaction_value"]) -> typing.Union[MetaOapg.properties.average_transaction_value, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["median_transaction_value"]) -> typing.Union[MetaOapg.properties.median_transaction_value, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["transaction_count", "average_transaction_value", "median_transaction_value", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        transaction_count: typing.Union[MetaOapg.properties.transaction_count, decimal.Decimal, int, ],
        average_transaction_value: typing.Union[MetaOapg.properties.average_transaction_value, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        median_transaction_value: typing.Union[MetaOapg.properties.median_transaction_value, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelsUserTransactionsStatisticsResponse':
        return super().__new__(
            cls,
            *args,
            transaction_count=transaction_count,
            average_transaction_value=average_transaction_value,
            median_transaction_value=median_transaction_value,
            _configuration=_configuration,
            **kwargs,
        )
