# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hyperplane_python_sdk import schemas  # noqa: F401


class ModelsUserCashflowHistoryResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Historic of cashflows for a given user
    """


    class MetaOapg:
        required = {
            "user_id",
            "windows",
        }
        
        class properties:
            user_id = schemas.StrSchema
            
            
            class windows(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ModelsCashflowWindowStatistics']:
                        return ModelsCashflowWindowStatistics
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ModelsCashflowWindowStatistics'], typing.List['ModelsCashflowWindowStatistics']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'windows':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ModelsCashflowWindowStatistics':
                    return super().__getitem__(i)
            __annotations__ = {
                "user_id": user_id,
                "windows": windows,
            }
    
    user_id: MetaOapg.properties.user_id
    windows: MetaOapg.properties.windows
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["user_id"]) -> MetaOapg.properties.user_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["windows"]) -> MetaOapg.properties.windows: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["user_id", "windows", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["user_id"]) -> MetaOapg.properties.user_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["windows"]) -> MetaOapg.properties.windows: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["user_id", "windows", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        user_id: typing.Union[MetaOapg.properties.user_id, str, ],
        windows: typing.Union[MetaOapg.properties.windows, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelsUserCashflowHistoryResponse':
        return super().__new__(
            cls,
            *args,
            user_id=user_id,
            windows=windows,
            _configuration=_configuration,
            **kwargs,
        )

from hyperplane_python_sdk.model.models_cashflow_window_statistics import ModelsCashflowWindowStatistics
