# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hyperplane_python_sdk import schemas  # noqa: F401


class ModelsAutoMLRunUsersGetResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "user_scores",
        }
        
        class properties:
            
            
            class user_scores(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ModelsUserScore']:
                        return ModelsUserScore
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ModelsUserScore'], typing.List['ModelsUserScore']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'user_scores':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ModelsUserScore':
                    return super().__getitem__(i)
            last_scored_date = schemas.StrSchema
            __annotations__ = {
                "user_scores": user_scores,
                "last_scored_date": last_scored_date,
            }
    
    user_scores: MetaOapg.properties.user_scores
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["user_scores"]) -> MetaOapg.properties.user_scores: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["last_scored_date"]) -> MetaOapg.properties.last_scored_date: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["user_scores", "last_scored_date", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["user_scores"]) -> MetaOapg.properties.user_scores: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["last_scored_date"]) -> typing.Union[MetaOapg.properties.last_scored_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["user_scores", "last_scored_date", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        user_scores: typing.Union[MetaOapg.properties.user_scores, list, tuple, ],
        last_scored_date: typing.Union[MetaOapg.properties.last_scored_date, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelsAutoMLRunUsersGetResponse':
        return super().__new__(
            cls,
            *args,
            user_scores=user_scores,
            last_scored_date=last_scored_date,
            _configuration=_configuration,
            **kwargs,
        )

from hyperplane_python_sdk.model.models_user_score import ModelsUserScore
