# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hyperplane_python_sdk import schemas  # noqa: F401


class ModelsAutoMLRunsGetResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "runs",
        }
        
        class properties:
            
            
            class runs(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ModelsAutoMLRunSummary']:
                        return ModelsAutoMLRunSummary
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ModelsAutoMLRunSummary'], typing.List['ModelsAutoMLRunSummary']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'runs':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ModelsAutoMLRunSummary':
                    return super().__getitem__(i)
            __annotations__ = {
                "runs": runs,
            }
    
    runs: MetaOapg.properties.runs
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["runs"]) -> MetaOapg.properties.runs: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["runs", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["runs"]) -> MetaOapg.properties.runs: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["runs", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        runs: typing.Union[MetaOapg.properties.runs, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelsAutoMLRunsGetResponse':
        return super().__new__(
            cls,
            *args,
            runs=runs,
            _configuration=_configuration,
            **kwargs,
        )

from hyperplane_python_sdk.model.models_auto_ml_run_summary import ModelsAutoMLRunSummary
