# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hyperplane_python_sdk import schemas  # noqa: F401


class ModelsPersonaCreateResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "persona_id",
            "persona_name",
            "creation_datetime",
        }
        
        class properties:
            creation_datetime = schemas.StrSchema
            persona_id = schemas.StrSchema
            persona_name = schemas.StrSchema
            __annotations__ = {
                "creation_datetime": creation_datetime,
                "persona_id": persona_id,
                "persona_name": persona_name,
            }
    
    persona_id: MetaOapg.properties.persona_id
    persona_name: MetaOapg.properties.persona_name
    creation_datetime: MetaOapg.properties.creation_datetime
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["creation_datetime"]) -> MetaOapg.properties.creation_datetime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["persona_id"]) -> MetaOapg.properties.persona_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["persona_name"]) -> MetaOapg.properties.persona_name: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["creation_datetime", "persona_id", "persona_name", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["creation_datetime"]) -> MetaOapg.properties.creation_datetime: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["persona_id"]) -> MetaOapg.properties.persona_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["persona_name"]) -> MetaOapg.properties.persona_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["creation_datetime", "persona_id", "persona_name", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        persona_id: typing.Union[MetaOapg.properties.persona_id, str, ],
        persona_name: typing.Union[MetaOapg.properties.persona_name, str, ],
        creation_datetime: typing.Union[MetaOapg.properties.creation_datetime, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelsPersonaCreateResponse':
        return super().__new__(
            cls,
            *args,
            persona_id=persona_id,
            persona_name=persona_name,
            creation_datetime=creation_datetime,
            _configuration=_configuration,
            **kwargs,
        )
