# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import hyperplane_python_sdk
from hyperplane_python_sdk.paths.batch_user_personas import post
from hyperplane_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestBatchUserPersonas(ApiTestMixin, unittest.TestCase):
    """
    BatchUserPersonas unit test stubs
        Get all the facet attributes for a list of users.
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
