# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from hyperplane_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from hyperplane_python_sdk.api_response import AsyncGeneratorResponse
from hyperplane_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hyperplane_python_sdk import schemas  # noqa: F401

from hyperplane_python_sdk.model.models_timestamp_attribute_filter import ModelsTimestampAttributeFilter as ModelsTimestampAttributeFilterSchema
from hyperplane_python_sdk.model.models_post_persona_users_request_blocklist import ModelsPostPersonaUsersRequestBlocklist as ModelsPostPersonaUsersRequestBlocklistSchema
from hyperplane_python_sdk.model.models_persona_users_response import ModelsPersonaUsersResponse as ModelsPersonaUsersResponseSchema
from hyperplane_python_sdk.model.api_err_response import ApiErrResponse as ApiErrResponseSchema
from hyperplane_python_sdk.model.models_post_persona_users_request import ModelsPostPersonaUsersRequest as ModelsPostPersonaUsersRequestSchema
from hyperplane_python_sdk.model.models_numerical_attribute_filter import ModelsNumericalAttributeFilter as ModelsNumericalAttributeFilterSchema
from hyperplane_python_sdk.model.models_categorical_attribute_filter import ModelsCategoricalAttributeFilter as ModelsCategoricalAttributeFilterSchema

from hyperplane_python_sdk.type.api_err_response import ApiErrResponse
from hyperplane_python_sdk.type.models_numerical_attribute_filter import ModelsNumericalAttributeFilter
from hyperplane_python_sdk.type.models_timestamp_attribute_filter import ModelsTimestampAttributeFilter
from hyperplane_python_sdk.type.models_categorical_attribute_filter import ModelsCategoricalAttributeFilter
from hyperplane_python_sdk.type.models_persona_users_response import ModelsPersonaUsersResponse
from hyperplane_python_sdk.type.models_post_persona_users_request import ModelsPostPersonaUsersRequest
from hyperplane_python_sdk.type.models_post_persona_users_request_blocklist import ModelsPostPersonaUsersRequestBlocklist

from ...api_client import Dictionary
from hyperplane_python_sdk.pydantic.models_timestamp_attribute_filter import ModelsTimestampAttributeFilter as ModelsTimestampAttributeFilterPydantic
from hyperplane_python_sdk.pydantic.models_persona_users_response import ModelsPersonaUsersResponse as ModelsPersonaUsersResponsePydantic
from hyperplane_python_sdk.pydantic.models_categorical_attribute_filter import ModelsCategoricalAttributeFilter as ModelsCategoricalAttributeFilterPydantic
from hyperplane_python_sdk.pydantic.models_post_persona_users_request import ModelsPostPersonaUsersRequest as ModelsPostPersonaUsersRequestPydantic
from hyperplane_python_sdk.pydantic.models_post_persona_users_request_blocklist import ModelsPostPersonaUsersRequestBlocklist as ModelsPostPersonaUsersRequestBlocklistPydantic
from hyperplane_python_sdk.pydantic.api_err_response import ApiErrResponse as ApiErrResponsePydantic
from hyperplane_python_sdk.pydantic.models_numerical_attribute_filter import ModelsNumericalAttributeFilter as ModelsNumericalAttributeFilterPydantic

from . import path

# Query params


class PageNumberSchema(
    schemas.IntSchema
):


    class MetaOapg:
        inclusive_minimum = 1


class PageSizeSchema(
    schemas.IntSchema
):


    class MetaOapg:
        inclusive_maximum = 10000
        inclusive_minimum = 1
MonthSchema = schemas.StrSchema


class PersonaScoreThresholdSchema(
    schemas.NumberSchema
):


    class MetaOapg:
        inclusive_maximum = 1
        inclusive_minimum = 0
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'page_number': typing.Union[PageNumberSchema, decimal.Decimal, int, ],
        'page_size': typing.Union[PageSizeSchema, decimal.Decimal, int, ],
        'month': typing.Union[MonthSchema, str, ],
        'persona_score_threshold': typing.Union[PersonaScoreThresholdSchema, decimal.Decimal, int, float, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_page_number = api_client.QueryParameter(
    name="page_number",
    style=api_client.ParameterStyle.FORM,
    schema=PageNumberSchema,
    explode=True,
)
request_query_page_size = api_client.QueryParameter(
    name="page_size",
    style=api_client.ParameterStyle.FORM,
    schema=PageSizeSchema,
    explode=True,
)
request_query_month = api_client.QueryParameter(
    name="month",
    style=api_client.ParameterStyle.FORM,
    schema=MonthSchema,
    explode=True,
)
request_query_persona_score_threshold = api_client.QueryParameter(
    name="persona_score_threshold",
    style=api_client.ParameterStyle.FORM,
    schema=PersonaScoreThresholdSchema,
    explode=True,
)
# Header params
ModuleIdSchema = schemas.StrSchema
RequestRequiredHeaderParams = typing_extensions.TypedDict(
    'RequestRequiredHeaderParams',
    {
    }
)
RequestOptionalHeaderParams = typing_extensions.TypedDict(
    'RequestOptionalHeaderParams',
    {
        'module-id': typing.Union[ModuleIdSchema, str, ],
    },
    total=False
)


class RequestHeaderParams(RequestRequiredHeaderParams, RequestOptionalHeaderParams):
    pass


request_header_module_id = api_client.HeaderParameter(
    name="module-id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=ModuleIdSchema,
)
# Path params
PersonaIdSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'persona_id': typing.Union[PersonaIdSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_persona_id = api_client.PathParameter(
    name="persona_id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=PersonaIdSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationJson = ModelsPostPersonaUsersRequestSchema


request_body_models_post_persona_users_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
_auth = [
    'PASETO',
]
SchemaFor200ResponseBodyApplicationJson = ModelsPersonaUsersResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: ModelsPersonaUsersResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: ModelsPersonaUsersResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor400ResponseBodyApplicationJson = ApiErrResponseSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: ApiErrResponse


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: ApiErrResponse


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
SchemaFor404ResponseBodyApplicationJson = ApiErrResponseSchema


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: ApiErrResponse


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: ApiErrResponse


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '400': _response_for_400,
    '404': _response_for_404,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _get_ranked_users_mapped_args(
        self,
        blocklist: ModelsPostPersonaUsersRequestBlocklist,
        branch: ModelsCategoricalAttributeFilter,
        persona_id: str,
        birth_date: typing.Optional[ModelsTimestampAttributeFilter] = None,
        cbo_code: typing.Optional[ModelsCategoricalAttributeFilter] = None,
        declared_monthly_income: typing.Optional[ModelsNumericalAttributeFilter] = None,
        job_title: typing.Optional[ModelsCategoricalAttributeFilter] = None,
        module_id: typing.Optional[str] = None,
        page_number: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        month: typing.Optional[str] = None,
        persona_score_threshold: typing.Optional[typing.Union[int, float]] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _header_params = {}
        _path_params = {}
        _body = {}
        if birth_date is not None:
            _body["birth_date"] = birth_date
        if blocklist is not None:
            _body["blocklist"] = blocklist
        if branch is not None:
            _body["branch"] = branch
        if cbo_code is not None:
            _body["cbo_code"] = cbo_code
        if declared_monthly_income is not None:
            _body["declared_monthly_income"] = declared_monthly_income
        if job_title is not None:
            _body["job_title"] = job_title
        args.body = _body
        if page_number is not None:
            _query_params["page_number"] = page_number
        if page_size is not None:
            _query_params["page_size"] = page_size
        if month is not None:
            _query_params["month"] = month
        if persona_score_threshold is not None:
            _query_params["persona_score_threshold"] = persona_score_threshold
        if module_id is not None:
            _header_params["module-id"] = module_id
        if persona_id is not None:
            _path_params["persona_id"] = persona_id
        args.query = _query_params
        args.header = _header_params
        args.path = _path_params
        return args

    async def _aget_ranked_users_oapg(
        self,
        body: typing.Any = None,
            query_params: typing.Optional[dict] = {},
            header_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Get ranked list of users who match a persona definition.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestHeaderParams, header_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_persona_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_page_number,
            request_query_page_size,
            request_query_month,
            request_query_persona_score_threshold,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        for parameter in (
            request_header_module_id,
        ):
            parameter_data = header_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _headers.extend(serialized_data)
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/persona/{persona_id}/users',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_models_post_persona_users_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_ranked_users_oapg(
        self,
        body: typing.Any = None,
            query_params: typing.Optional[dict] = {},
            header_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Get ranked list of users who match a persona definition.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestHeaderParams, header_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_persona_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_page_number,
            request_query_page_size,
            request_query_month,
            request_query_persona_score_threshold,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        for parameter in (
            request_header_module_id,
        ):
            parameter_data = header_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _headers.extend(serialized_data)
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/persona/{persona_id}/users',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_models_post_persona_users_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetRankedUsersRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_ranked_users(
        self,
        blocklist: ModelsPostPersonaUsersRequestBlocklist,
        branch: ModelsCategoricalAttributeFilter,
        persona_id: str,
        birth_date: typing.Optional[ModelsTimestampAttributeFilter] = None,
        cbo_code: typing.Optional[ModelsCategoricalAttributeFilter] = None,
        declared_monthly_income: typing.Optional[ModelsNumericalAttributeFilter] = None,
        job_title: typing.Optional[ModelsCategoricalAttributeFilter] = None,
        module_id: typing.Optional[str] = None,
        page_number: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        month: typing.Optional[str] = None,
        persona_score_threshold: typing.Optional[typing.Union[int, float]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_ranked_users_mapped_args(
            blocklist=blocklist,
            branch=branch,
            persona_id=persona_id,
            birth_date=birth_date,
            cbo_code=cbo_code,
            declared_monthly_income=declared_monthly_income,
            job_title=job_title,
            module_id=module_id,
            page_number=page_number,
            page_size=page_size,
            month=month,
            persona_score_threshold=persona_score_threshold,
        )
        return await self._aget_ranked_users_oapg(
            body=args.body,
            query_params=args.query,
            header_params=args.header,
            path_params=args.path,
            **kwargs,
        )
    
    def get_ranked_users(
        self,
        blocklist: ModelsPostPersonaUsersRequestBlocklist,
        branch: ModelsCategoricalAttributeFilter,
        persona_id: str,
        birth_date: typing.Optional[ModelsTimestampAttributeFilter] = None,
        cbo_code: typing.Optional[ModelsCategoricalAttributeFilter] = None,
        declared_monthly_income: typing.Optional[ModelsNumericalAttributeFilter] = None,
        job_title: typing.Optional[ModelsCategoricalAttributeFilter] = None,
        module_id: typing.Optional[str] = None,
        page_number: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        month: typing.Optional[str] = None,
        persona_score_threshold: typing.Optional[typing.Union[int, float]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_ranked_users_mapped_args(
            blocklist=blocklist,
            branch=branch,
            persona_id=persona_id,
            birth_date=birth_date,
            cbo_code=cbo_code,
            declared_monthly_income=declared_monthly_income,
            job_title=job_title,
            module_id=module_id,
            page_number=page_number,
            page_size=page_size,
            month=month,
            persona_score_threshold=persona_score_threshold,
        )
        return self._get_ranked_users_oapg(
            body=args.body,
            query_params=args.query,
            header_params=args.header,
            path_params=args.path,
        )

class GetRankedUsers(BaseApi):

    async def aget_ranked_users(
        self,
        blocklist: ModelsPostPersonaUsersRequestBlocklist,
        branch: ModelsCategoricalAttributeFilter,
        persona_id: str,
        birth_date: typing.Optional[ModelsTimestampAttributeFilter] = None,
        cbo_code: typing.Optional[ModelsCategoricalAttributeFilter] = None,
        declared_monthly_income: typing.Optional[ModelsNumericalAttributeFilter] = None,
        job_title: typing.Optional[ModelsCategoricalAttributeFilter] = None,
        module_id: typing.Optional[str] = None,
        page_number: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        month: typing.Optional[str] = None,
        persona_score_threshold: typing.Optional[typing.Union[int, float]] = None,
        validate: bool = False,
        **kwargs,
    ) -> ModelsPersonaUsersResponsePydantic:
        raw_response = await self.raw.aget_ranked_users(
            blocklist=blocklist,
            branch=branch,
            persona_id=persona_id,
            birth_date=birth_date,
            cbo_code=cbo_code,
            declared_monthly_income=declared_monthly_income,
            job_title=job_title,
            module_id=module_id,
            page_number=page_number,
            page_size=page_size,
            month=month,
            persona_score_threshold=persona_score_threshold,
            **kwargs,
        )
        if validate:
            return ModelsPersonaUsersResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(ModelsPersonaUsersResponsePydantic, raw_response.body)
    
    
    def get_ranked_users(
        self,
        blocklist: ModelsPostPersonaUsersRequestBlocklist,
        branch: ModelsCategoricalAttributeFilter,
        persona_id: str,
        birth_date: typing.Optional[ModelsTimestampAttributeFilter] = None,
        cbo_code: typing.Optional[ModelsCategoricalAttributeFilter] = None,
        declared_monthly_income: typing.Optional[ModelsNumericalAttributeFilter] = None,
        job_title: typing.Optional[ModelsCategoricalAttributeFilter] = None,
        module_id: typing.Optional[str] = None,
        page_number: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        month: typing.Optional[str] = None,
        persona_score_threshold: typing.Optional[typing.Union[int, float]] = None,
        validate: bool = False,
    ) -> ModelsPersonaUsersResponsePydantic:
        raw_response = self.raw.get_ranked_users(
            blocklist=blocklist,
            branch=branch,
            persona_id=persona_id,
            birth_date=birth_date,
            cbo_code=cbo_code,
            declared_monthly_income=declared_monthly_income,
            job_title=job_title,
            module_id=module_id,
            page_number=page_number,
            page_size=page_size,
            month=month,
            persona_score_threshold=persona_score_threshold,
        )
        if validate:
            return ModelsPersonaUsersResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(ModelsPersonaUsersResponsePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        blocklist: ModelsPostPersonaUsersRequestBlocklist,
        branch: ModelsCategoricalAttributeFilter,
        persona_id: str,
        birth_date: typing.Optional[ModelsTimestampAttributeFilter] = None,
        cbo_code: typing.Optional[ModelsCategoricalAttributeFilter] = None,
        declared_monthly_income: typing.Optional[ModelsNumericalAttributeFilter] = None,
        job_title: typing.Optional[ModelsCategoricalAttributeFilter] = None,
        module_id: typing.Optional[str] = None,
        page_number: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        month: typing.Optional[str] = None,
        persona_score_threshold: typing.Optional[typing.Union[int, float]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_ranked_users_mapped_args(
            blocklist=blocklist,
            branch=branch,
            persona_id=persona_id,
            birth_date=birth_date,
            cbo_code=cbo_code,
            declared_monthly_income=declared_monthly_income,
            job_title=job_title,
            module_id=module_id,
            page_number=page_number,
            page_size=page_size,
            month=month,
            persona_score_threshold=persona_score_threshold,
        )
        return await self._aget_ranked_users_oapg(
            body=args.body,
            query_params=args.query,
            header_params=args.header,
            path_params=args.path,
            **kwargs,
        )
    
    def post(
        self,
        blocklist: ModelsPostPersonaUsersRequestBlocklist,
        branch: ModelsCategoricalAttributeFilter,
        persona_id: str,
        birth_date: typing.Optional[ModelsTimestampAttributeFilter] = None,
        cbo_code: typing.Optional[ModelsCategoricalAttributeFilter] = None,
        declared_monthly_income: typing.Optional[ModelsNumericalAttributeFilter] = None,
        job_title: typing.Optional[ModelsCategoricalAttributeFilter] = None,
        module_id: typing.Optional[str] = None,
        page_number: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        month: typing.Optional[str] = None,
        persona_score_threshold: typing.Optional[typing.Union[int, float]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_ranked_users_mapped_args(
            blocklist=blocklist,
            branch=branch,
            persona_id=persona_id,
            birth_date=birth_date,
            cbo_code=cbo_code,
            declared_monthly_income=declared_monthly_income,
            job_title=job_title,
            module_id=module_id,
            page_number=page_number,
            page_size=page_size,
            month=month,
            persona_score_threshold=persona_score_threshold,
        )
        return self._get_ranked_users_oapg(
            body=args.body,
            query_params=args.query,
            header_params=args.header,
            path_params=args.path,
        )

