# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from hyperplane_python_sdk.paths.automl_lookalike.post import CreateLookalikeRequestRaw
from hyperplane_python_sdk.paths.automl_runs.get import GetAllRunsRaw
from hyperplane_python_sdk.paths.automl_users.get import GetAvailableUsersRaw
from hyperplane_python_sdk.paths.automl_runs_run_id_status.get import GetRunStatusRaw
from hyperplane_python_sdk.paths.automl_runs_run_id_status_batch_scores.get import GetRunStatusBatchScoresRaw
from hyperplane_python_sdk.paths.automl_runs_run_id.get import GetRunSummaryRaw
from hyperplane_python_sdk.paths.automl_runs_run_id_users.post import GetTopUsersExcludingTrainingRaw
from hyperplane_python_sdk.paths.automl_runs_run_id_rescore.post import RerunInferenceRaw
from hyperplane_python_sdk.paths.automl_runs_run_id_generate_batch_scores.post import RerunInferenceScoresRaw


class AutoMLServiceApiRaw(
    CreateLookalikeRequestRaw,
    GetAllRunsRaw,
    GetAvailableUsersRaw,
    GetRunStatusRaw,
    GetRunStatusBatchScoresRaw,
    GetRunSummaryRaw,
    GetTopUsersExcludingTrainingRaw,
    RerunInferenceRaw,
    RerunInferenceScoresRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
