# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from hyperplane_python_sdk.paths.client_access_key_id.get import GetByAccessKey
from hyperplane_python_sdk.apis.tags.client_api_raw import ClientApiRaw


class ClientApi(
    GetByAccessKey,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ClientApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ClientApiRaw(api_client)
