# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from hyperplane_python_sdk.paths.health.get import CheckStatus
from hyperplane_python_sdk.apis.tags.health_api_raw import HealthApiRaw


class HealthApi(
    CheckStatus,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: HealthApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = HealthApiRaw(api_client)
