# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from hyperplane_python_sdk.paths.statistics_latest_month.get import GetLatestMonth
from hyperplane_python_sdk.apis.tags.statistics_api_raw import StatisticsApiRaw


class StatisticsApi(
    GetLatestMonth,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: StatisticsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = StatisticsApiRaw(api_client)
