# coding: utf-8

"""
    Hyperplane API Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from hyperplane_python_sdk.paths.batch_user_personas.post import GetAllFacetAttributes
from hyperplane_python_sdk.paths.users_user_id_personas.get import ListUserPersonas
from hyperplane_python_sdk.apis.tags.users_api_raw import UsersApiRaw


class UsersApi(
    GetAllFacetAttributes,
    ListUserPersonas,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UsersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UsersApiRaw(api_client)
